Repository dineshUmasankar/YARTBML, pull requests merged in 2024-04, with the labels that each got.

#15 Lexer & Initial REPL
  src/go.mod
  src/lexer/lexer.go
  src/lexer/lexer_test.go
  src/main.go
  src/repl/repl.go
  src/token/token.go
Labels: enhancement

#17 feat: Commit Generated Documentation Artifacts back into repository
  .github/workflows/documentation-release.yml
Labels: documentation

#18 feat: parsing let statements
  .gitignore
  src/ast/ast.go
  src/lexer/lexer.go
  src/parser/parser.go
  src/parser/parser_test.go
  src/repl/repl.go
  src/token/token.go
Labels: enhancement

#21 feat: Parse Return Statement(s)
  src/ast/ast.go
  src/parser/parser.go
  src/parser/parser_test.go
Labels: enhancement

#23 feat!: File Restructure & Initial VSCode Plugin [Syntax Highlighting]
  demonstrations/outlines/final-preliminary-presentation.md
  demonstrations/presentations/final-preliminary-presentation/.gitignore
  demonstrations/presentations/final-preliminary-presentation/.npmrc
  demonstrations/presentations/final-preliminary-presentation/README.md
  demonstrations/presentations/final-preliminary-presentation/final-preliminary-presentation.pdf
  demonstrations/presentations/final-preliminary-presentation/netlify.toml
  demonstrations/presentations/final-preliminary-presentation/package.json
  demonstrations/presentations/final-preliminary-presentation/pnpm-lock.yaml
  demonstrations/presentations/final-preliminary-presentation/public/docgen.png
  demonstrations/presentations/final-preliminary-presentation/public/golang.png
  demonstrations/presentations/final-preliminary-presentation/public/tbook.png
  demonstrations/presentations/final-preliminary-presentation/slides.md
  demonstrations/presentations/final-preliminary-presentation/vercel.json
  examples/helloworld.ybml
  internal/ast/ast.go
  internal/ast/ast_test.go
  internal/go.mod
  internal/lexer/lexer.go
  internal/lexer/lexer_test.go
  internal/main.go
  internal/parser/parser.go
  internal/parser/parser_test.go
  internal/repl/repl.go
  internal/token/token.go
  tooling/vscode/yartbml-syntax/.vscode/launch.json
  tooling/vscode/yartbml-syntax/.vscodeignore
  tooling/vscode/yartbml-syntax/CHANGELOG.md
  tooling/vscode/yartbml-syntax/README.md
  tooling/vscode/yartbml-syntax/language-configuration.json
  tooling/vscode/yartbml-syntax/package.json
  tooling/vscode/yartbml-syntax/syntaxes/ybml.tmLanguage.json
  tooling/vscode/yartbml-syntax/vsc-extension-quickstart.md
Labels: enhancement

#25 bug: switch case in parser for statements
  internal/parser/parser.go
Labels: bug

#26 feat: Parse Infix Expressions
  internal/ast/ast.go
  internal/parser/parser.go
  internal/parser/parser_test.go
Labels: enhancement

#28 feat: Parse Grouped Expressions
  internal/ast/ast.go
  internal/parser/parser.go
  internal/parser/parser_test.go
Labels: enhancement

#29 feat: Parse If Expressions & Block Statements
  internal/ast/ast.go
  internal/parser/parser.go
  internal/parser/parser_test.go
Labels: enhancement

#30 feat: Parse Function Literals
  internal/ast/ast.go
  internal/parser/parser.go
  internal/parser/parser_test.go
Labels: enhancement

#31 feat: Parse Function Calls
  internal/ast/ast.go
  internal/parser/parser.go
  internal/parser/parser_test.go
Labels: enhancement

#32 feat: Parse Expressions in Let & Return (Cleanup)
  internal/parser/parser.go
  internal/parser/parser_test.go
Labels: enhancement

#46 feat: Initial VSCode Language Support Extension [Syntax Highlighting]
  examples/add.ybml
  examples/datatypes.ybml
  examples/fibonacci.ybml
  examples/helloworld.ybml
  examples/maximum.ybml
  examples/minimum.ybml
  tooling/vscode/yartbml-syntax/CHANGELOG.md
  tooling/vscode/yartbml-syntax/README.md
  tooling/vscode/yartbml-syntax/package.json
  tooling/vscode/yartbml-syntax/syntaxes/ybml.tmLanguage.json
  tooling/vscode/yartbml-syntax/vsc-extension-quickstart.md
  tooling/vscode/yartbml/.vscode/launch.json
  tooling/vscode/yartbml/.vscodeignore
  tooling/vscode/yartbml/CHANGELOG.md
  tooling/vscode/yartbml/LICENSE.md
  tooling/vscode/yartbml/README.md
  tooling/vscode/yartbml/assets/logo.png
  tooling/vscode/yartbml/extension-documentation.md
  tooling/vscode/yartbml/language-configuration.json
  tooling/vscode/yartbml/package.json
  tooling/vscode/yartbml/syntaxes/ybml.tmLanguage.json
  tooling/vscode/yartbml/yartbml-0.0.1.vsix
Labels: enhancement

#42 Extending interpreter
  internal/ast/ast.go
  internal/evaluator/builtins.go
  internal/evaluator/evaluator.go
  internal/evaluator/evaluator_test.go
  internal/lexer/lexer.go
  internal/lexer/lexer_test.go
  internal/object/environment.go
  internal/object/object.go
  internal/object/object_test.go
  internal/parser/parser.go
  internal/parser/parser_test.go
  internal/token/token.go
Labels: enhancement
